"""add_hotel_name_to_search_history

Revision ID: b7a376931a82
Revises: fa349a8675d8
Create Date: 2026-08-03 18:56:29.512640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7a376931a82'
down_revision: Union[str, Sequence[str], None] = 'fa349a8675d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotel_search_history', sa.Column('hotel_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hotel_search_history', 'hotel_name')
    # ### end Alembic commands ###
